name: Cleanup Backend Tests

on:
  pull_request:
    branches:
      - dev
      - qa

jobs:
  cleanup_check:
    runs-on: ubuntu-latest
    name: cleanup_check

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: cleanup check
      run: npm run cleanup:check
